spring.application.name=resolve-it-backend

spring.datasource.url=jdbc:mysql://localhost:3306/resolveit_db
spring.datasource.username=root
spring.datasource.password=thanvi@26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

# OpenAI API Key (replace with your real key)
openai.api.key=sk-REPLACE_WITH_YOUR_KEY